#!/usr/bin/env python

import json
import sys


for filename in sys.argv[1:]:
    try:
        with open(filename) as f:
            json.load(f)
        print "OK - %s" % filename
    except Exception as e:
        print "Error - %s" % filename
        print str(e)
